runtime: nodejs20

env_variables:
  MONGO_URI: "mongodb+srv://Rainas:1405raina@cluster0.3kjzt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  NODE_ENV: "production"

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
